title: SAP CODE ì•„ì¹´ë°ë¯¸
description: SAP CODE ì•„ì¹´ë°ë¯¸ í•™ìŠµ ì •ë¦¬ ì‚¬ì´íŠ¸

remote_theme: just-the-docs/just-the-docs

# ğŸ‘‰ github.io ì‚¬ì´íŠ¸ ì£¼ì†Œì™€ ë¦¬í¬ì§€í† ë¦¬ ê²½ë¡œ
url: https://idanakyoung.github.io
baseurl: /sapcode

# (ì¤‘ìš”) ì›ê²© í…Œë§ˆ í”ŒëŸ¬ê·¸ì¸ ì‚¬ìš©
plugins:
  - jekyll-remote-theme

# ì˜µì…˜
search_enabled: true
aux_links:
  GitHub Repo: https://github.com/idanakyoung/sapcode
footer_content: "Â© 2025 SAP CODE â€” ê¸°ë¡ì€ ìµœê³ ì˜ ë³µìŠµ"
