title: SAP CODE ì•„ì¹´ë°ë¯¸
description: SAP CODE ì•„ì¹´ë°ë¯¸ í•™ìŠµ ì •ë¦¬ ì‚¬ì´íŠ¸

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://idanakyoung.github.io
baseurl: /sapcode

# ğŸ”¹ ì—¬ê¸°ë¶€í„° ì»¤ìŠ¤í„°ë§ˆì´ì§•
color_scheme: sapcode         # ì•„ë˜ì—ì„œ ë§Œë“œëŠ” ë‚˜ë§Œì˜ íŒ”ë ˆíŠ¸ ì´ë¦„
logo: /assets/img/logo.png    # ì—†ìœ¼ë©´ ìë™ìœ¼ë¡œ ê¸€ì ë¡œê³ 
favicon_ico: /assets/img/favicon.ico

search_enabled: true
back_to_top: true
back_to_top_text: "ë§¨ ìœ„ë¡œ"
heading_anchors: true

aux_links:
  GitHub Repo: https://github.com/idanakyoung/sapcode
footer_content: "Â© 2025 SAP CODE â€” ê¸°ë¡ì€ ìµœê³ ì˜ ë³µìŠµ"
