title: sapcode
description: SAP CODE ì•„ì¹´ë°ë¯¸ ê³µë¶€ ì •ë¦¬

# theme: minima
remote_theme: pages-themes/cayman@v0.2.0

# GitHub Pages ì£¼ì†Œ: https://idanakyoung.github.io/sapcode/
url: "https://idanakyoung.github.io"
baseurl: "/sapcode"

# ğŸ”¹ ìƒë‹¨ íƒ­ì— ë³´ì—¬ì¤„ í˜ì´ì§€ë“¤ (SAP Help Portal ëŠë‚Œ)
header_pages:
  - index.md
  - studies/ux1/index.md
  - studies/abap1/index.md
  - studies/abap2/index.md
  - studies/abap3/index.md
  - studies/ux23/index.md
  - studies/project/index.md
  - studies/jobfair/index.md

markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
